source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XLEasyKit_Example', :exclusive => true do
  pod "XLEasyKit", :path => "../"
end

target 'XLEasyKit_Tests', :exclusive => true do
  pod "XLEasyKit", :path => "../"

  
end
